### ISSUE TITLE
Recommendation: Example Project

### ISSUE THREAD

**Issue by ghost** [preplay/i18next-ios#3]
I think it would be useful to setup a project for this particular library which aims at creating a comprehensive example that allows others to quickly start using the project. If this sounds good, maybe we would start by discussing what we would want to include in a such an example. Thoughts?

**Comment by ghost** [comment]
Closing, dead issue. Recommendation still stands.

**Comment by rafaelmaeuer** [comment]
This feature is really necessary, the setup is not self explaining!
